config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'animals#index'
    resources:animals do
      resources:sightings
    end
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many:sightings, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sighting.rb
class Sighting < ApplicationRecord
  
  belongs_to :animal
    enum region: [:north, :east, :south, :west]
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

    def index
        @animals = Animal.all
    end

    def show
        @animal = Animal.find(params[:id])
    end

    def new
        @animal = Animal.new
    end

    def edit
        @animal = Animal.find(params[:id])
    end

    def create
        @animal = Animal.create(animal_params)
        if @animal.save
            redirect_to animals_path
        else
            render 'new'
        end
    end

    def update
        @animal = Animal.find(params[:id])

        if @animal.update(animal_params)
          redirect_to animals_path
        else
          render 'edit'
        end
    end

    def destroy
        @animal = Animal.find(params[:id])
        @animal.destroy
        redirect_to animals_path(@animal)
    end

    private
      def animal_params
          params.require(:animal).permit(:animal_name)
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController

  def index

  end

  def new
      @animal = Animal.find(params[:animal_id])
      @sighting = @animal.sightings.new
  end

  def edit
      @sighting = Sighting.find(params[:id])
      @animal = @sighting.animal
  end

  def create
      @animal = Animal.find(params[:animal_id])
      @sighting = @animal.sightings.create(sighting_params)

      if @sighting.save
        redirect_to animal_path(@animal)
      else
        render 'new'
      end
  end

   def update
      @sighting = Sighting.find(params[:id])
      @animal = @sighting.animal

      if @sighting.update(sighting_params)
          redirect_to animal_path(@animal)
      else
          render 'edit'
      end
   end

   def destroy
      @sighting = Sighting.find(params[:id])
      @animal = @sighting.animal
      @sighting.destroy
      redirect_to animal_path(@animal)
   end

  private
    def sighting_params
        params.require(:sighting).permit(:date, :latitude, :longitude, :region)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/animals/_form.html.slim
= form_with(model: @animal, local: true) do |form|
  = form.label :'Animals name'
  br
  = form.text_field :animal_name
  br
  = form.submit

app/views/animals/edit.html.slim
h3 Edit Animal data

= render 'form'

app/views/animals/index.html.slim
h3 Animals list

= link_to 'new', new_animal_path

table
    tr
      th id
      th name
      - @animals.each do |animal|
        tr
            td
              = animal.id
            td
              = animal.animal_name
            td
              = link_to 'Show', animal_path(animal)
            td
              = link_to 'Edit', edit_animal_path(animal)
            td
              = link_to 'Add', new_animal_sighting_path(animal)
            td
              = link_to 'Delete', animal_path(animal), method: :delete, data: {confirm: 'Are yuh sure, yuh want to delete ?'}

app/views/animals/new.html.slim
h3 Enter Animal data

= render 'form'

app/views/animals/show.html.slim
h4 Animal

p = "id is #{@animal.id}"
p = "name #{@animal.animal_name}"

= link_to 'index', animals_path

table
    tr
      th Id
      th Date
      th latitude
      th longitude
      th region
    - @animal.sightings.each do |sighting|
        tr
          td
            = sighting.id
          td
            = sighting.date
          td
            = sighting.latitude
          td
            = sighting.longitude
          td
            = sighting.region
          td
            = link_to 'Add', new_animal_sighting_path(@animal, sighting)
          td
            = link_to 'Edit', edit_animal_sighting_path(@animal, sighting)
          td
            = link_to 'Delete',animal_sighting_path(@animal, sighting), method: :delete, data: {confirm: 'are yuh sure ?'}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wildlifeslim</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sightings/_form.html.slim
= form_with(model: [@animal, @sighting], local: true) do |form|
  = form.label :Date
  br
  = form.date_field :date
  br
  = form.label :latitude
  br
  = form.text_field :latitude
  br
  = form.label :longitude
  br
  = form.text_field :longitude
  br
  = form.label :regions
  br
  = form.select :region, Sighting.regions.keys
  br
  = form.submit

app/views/sightings/edit.html.slim
h3 Edit details

= render 'form'

app/views/sightings/new.html.slim
h3 Add animal sighting

= render 'form'